### ISSUE TITLE
Training Error 

### ISSUE THREAD

**Issue by thanhdo99** [keonlee9420/DiffSinger#1]
In this case, , i ran the scripts _python3 train.py -p config/vietnam/preprocess.yaml -m config/vietnam/model.yaml -t config/vietnam/train.yaml_
  File "train.py", line 199, in <module>
    main(args, configs)
  File "train.py", line 85, in main
    losses = Loss(batch, output)
  File "/home/thanhdo/envs/diffsinger_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/thanhdo/Documents/DiffSinger/model/loss.py", line 69, in forward
    log_duration_targets = log_duration_targets.masked_select(src_masks)
RuntimeError: The size of tensor a (39) must match the size of tensor b (136) at non-singleton dimension 1

![Screen Shot 2021-06-23 at 3 56 10 PM](https://user-images.githubusercontent.com/57792502/123067885-969d9200-d43b-11eb-8718-b28319952239.png)

**Comment by keonlee9420** [comment]
Hi @thanhdo99  , I didn't check the parallel training yet. If you have several GPUs inserted, please specify a single GPU by
CUDA_VISIBLE_DEVICES=<GPU index> as follows:

`CUDA_VISIBLE_DEVICES=0 python3 train.py -p config/vietnam/preprocess.yaml -m config/vietnam/model.yaml -t config/vietnam/train.yaml`
, which will run the code on the first GPU.

**Comment by thanhdo99** [comment]
Hi @keonlee9420 
i have tried as much as i can however, it still appears to be the same old problem as the last time
![Screen Shot 2021-06-23 at 5 54 04 PM](https://user-images.githubusercontent.com/57792502/123085172-25b2a600-d44c-11eb-9179-b158f88f02e9.png)

**Comment by keonlee9420** [comment]
I see. Can you print and share the shape of `log_duration_targets` and `src_masks`? And what's the option for `config["preprocessing"]["pitch"]["feature"]` and `config["preprocessing"]["energy"]["feature"]`?

**Comment by thanhdo99** [comment]
Here, thanks a lot bro

<img width="443" alt="Screen Shot 2021-06-24 at 2 53 18 PM" src="https://user-images.githubusercontent.com/57792502/123224671-3d496780-d4fc-11eb-8bdd-5ea16eda684e.png">
<img width="937" alt="Screen Shot 2021-06-24 at 2 42 18 PM" src="https://user-images.githubusercontent.com/57792502/123224678-3fabc180-d4fc-11eb-8b33-956cd94389e3.png">

**Comment by keonlee9420** [comment]
Umm, did you follow the process described in README.md for preprocessing your dataset? If so, your `src_masks` should have the same shape as `log_duration_targets`. Also, it would be helpful to check whether your data loader works correctly (in other words, duration information and input phoneme sequence should be aligned in each minibatch).

**Comment by thanhdo99** [comment]
when I used the Fastspeech 2 model ([https://github.com/ming024/FastSpeech2](url)) the result was noised like this below
 hifi-gan [https://drive.google.com/file/d/1QAWD9f9HYX1dNlojjUXtxi9p0QRAygQ6/view?usp=sharing](url) 
       mel-gan [https://drive.google.com/file/d/1tWBhH8ekGUYCX8YzH8dugi1KMofM7vfH/view?usp=sharing](url)

And I wonder if your diffsinger model could help me fix this problem?
Thanks

**Comment by keonlee9420** [comment]
Did you also train the vocoders under the dataset? If not, I recommend to train the vocoder too. I think the noise can be from either 1. an insufficient amount of dataset or 2. mismatch between synthesizer and vocoder. If both problems are not fixed, then the diffsinger model may show similar issues since it is a synthesizer and have 2 stage pipeline (synthesizer-vocoder).

**Comment by keonlee9420** [comment]
Close the issue due to the inactivity. you can reopen it anytime if you have issues.
