### ISSUE TITLE
have you try using sing data？

### ISSUE THREAD

**Issue by daxiangpanda** [keonlee9420/DiffSinger#2]
have you try using sing data？

**Comment by keonlee9420** [comment]
hi @daxiangpanda , I didn’t test the singing dataset (that’s why it is TTS extension). You may need to change the overall preprocessing flow and model architecture as well based on what the paper said for singing voice modeling.

**Comment by daxiangpanda** [comment]
thank you for your reply.Will try singing dataset next week.

**Comment by keonlee9420** [comment]
Great! I'm looking forward to the results, and it would be nice if you can PR them as well.

**Comment by keonlee9420** [comment]
Closed due to inactivity

**Comment by lvZic** [comment]
> thank you for your reply.Will try singing dataset next week.

hi, have u got good result by singing data?
