### ISSUE TITLE
diffusion_projection in ResidualBlock

### ISSUE THREAD

**Issue by tebin** [keonlee9420/DiffSinger#3]
Your implementation has `diffusion_projection` for every residual block similar to [DiffWave](https://arxiv.org/pdf/2009.09761.pdf), but this is inconsistent with the paper as the original architecture directly adds E_t (output of the step embedding module) to the input before the first convolution layer. Is there a reason behind this change?

**Comment by keonlee9420** [comment]
Hi @tebin , sorry for the late response.
There is no special reason for that. I just borrowed the idea from them and let the model learn in an expected way. But I think the method in the paper might work better somehow, and if you have a room for it, it would be nice if you can try them and share the results for others.
